### ISSUE TITLE
No pipe support

### ISSUE THREAD

**Issue by Ilya87** [Rolinh/VQMT#6]
Add please support for named pipes, so one could use ffmpeg for comparison. And not waste time and disk space for comparison.

**Comment by CoalZombik** [comment]
Although it is a some years since the opening of this issue, but I found this repository today and I need pipe support, because reading raw YUV file from HDD is too slow.

Because adding pipe support is easy to implement (only a few lines), I made pull request with this enhancement.

I hope, that this change is helpful.
