### ISSUE TITLE
Question: Version of VQMT code

### ISSUE THREAD

**Issue by Jeegarp** [Rolinh/VQMT#9]
VQMT official project shares its code at https://mmspg.epfl.ch/files/content/sites/mmspl/files/shared/VQMT/VQMT_Sources.rar 

So does the VQMT code used here is in sync with official codebase?

**Comment by rolinh** [comment]
Hi @Jeegarp,

The code at MMSPG hasn't changed since 2013. So you could say that it is in sync. :grinning: 
This repository however adds a Makefile to make it easy to compile the project without VisualStudio and on different platforms than Windows such as Linux. There are also a few fixes here and there as you can see by going through the list of commits.
